# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ASUS\OneDrive\Desktop\C21\gui\gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot
from pyqtgraph.ptime import time

import pyqtgraph as pg
import serial
import math
import sys
import os
import numpy as np
import threading
from random import randint

#define
NameCOM = []  
ser = []       
receive_data = []
comconnect = False   # check connect
Baudrate = 0    
axis = [10,0,0]
Y_min = -110
Y_max = 110
i = 0


Stopdata = '0'
Manualdata = '1'
Autodata = '2'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 20, 201, 151))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.label.setObjectName("label")
        self.COM = QtWidgets.QComboBox(self.groupBox_2)
        self.COM.setGeometry(QtCore.QRect(60, 20, 141, 21))
        self.COM.setObjectName("COM")
        self.COM.addItem("")
        self.COM.addItem("")
        self.COM.addItem("")
        self.COM.addItem("")
        self.COM.addItem("")
        self.COM.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(60, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 180, 201, 221))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.Manual = QtWidgets.QPushButton(self.groupBox_3)
        self.Manual.setGeometry(QtCore.QRect(20, 20, 171, 51))
        self.Manual.setObjectName("Manual")
        self.Auto = QtWidgets.QPushButton(self.groupBox_3)
        self.Auto.setGeometry(QtCore.QRect(20, 90, 171, 51))
        self.Auto.setObjectName("Auto")
        self.Stop = QtWidgets.QPushButton(self.groupBox_3)
        self.Stop.setGeometry(QtCore.QRect(20, 160, 171, 51))
        self.Stop.setObjectName("Stop")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(0, 400, 201, 161))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(210, 10, 531, 281))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.re_se_data = QtWidgets.QTextBrowser(self.groupBox_10)
        self.re_se_data.setEnabled(False)
        self.re_se_data.setGeometry(QtCore.QRect(10, 20, 511, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.re_se_data.sizePolicy().hasHeightForWidth())
        self.re_se_data.setSizePolicy(sizePolicy)
        self.re_se_data.setObjectName("re_se_data")
        self.testsend = QtWidgets.QTextEdit(self.groupBox_10)
        self.testsend.setEnabled(False)
        self.testsend.setGeometry(QtCore.QRect(10, 240, 431, 31))
        self.testsend.setObjectName("testsend")
        self.send = QtWidgets.QPushButton(self.groupBox_10)
        self.send.setEnabled(False)
        self.send.setGeometry(QtCore.QRect(450, 240, 71, 31))
        self.send.setObjectName("send")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 290, 531, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.xaxis = PlotWidget(self.groupBox_4)
        self.xaxis.setGeometry(QtCore.QRect(10, 20, 511, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xaxis.sizePolicy().hasHeightForWidth())
        self.xaxis.setSizePolicy(sizePolicy)
        self.xaxis.setObjectName("xaxis")
        self.xaxis_3 = PlotWidget(self.xaxis)
        self.xaxis_3.setGeometry(QtCore.QRect(30, 230, 251, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xaxis_3.sizePolicy().hasHeightForWidth())
        self.xaxis_3.setSizePolicy(sizePolicy)
        self.xaxis_3.setObjectName("xaxis_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.ser = serial.Serial()      
        self.retranslateUi(MainWindow)

        #connect serial
        self.pushButton.clicked.connect(self.clickedCONNECT) 
        
        #recive data
        self.send.clicked.connect(self.clickedSEND) 

        #enter mode manual
        self.Manual.clicked.connect(self.clickedManual) 
        self.Auto.clicked.connect(self.clickedAuto)
        self.Stop.clicked.connect(self.clickedStop)

        #set up graph
        self.xaxis.setBackground('w')
        self.xaxis.showGrid(x=True, y=True)
        self.xaxis.setYRange(Y_min, Y_max, padding=0)
        self.xaxis.setMouseEnabled(x=False, y=False)

        #set time
        self.x = list(range(100)) 
        self.y = list(range(100)) #[randint(0,100) for _ in range(100)] 
        self.timer = QtCore.QTimer()
        self.timer.setInterval(16)
        self.timer.timeout.connect(self.update)
        pen = pg.mkPen(color=(255,0,0))
        self.data_line = self.xaxis.plot(self.x, self.y, pen=pen)

        #set time for recive function
        self.timer_getdata = QtCore.QTimer()
        self.timer_getdata.setInterval(100)
        self.timer_getdata.timeout.connect(self.recive)

        # set time for stop system
        # self.timer_stop_sys = QtCore.QTimer()
        # self.timer_stop_sys.setInterval(100)
        # self.timer_stop_sys.timeout.connect(self.clickedCONNECT)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI for..."))
        self.groupBox.setTitle(_translate("MainWindow", "SERIAL"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.COM.setItemText(0, _translate("MainWindow", "COM1"))
        self.COM.setItemText(1, _translate("MainWindow", "COM2"))
        self.COM.setItemText(2, _translate("MainWindow", "COM3"))
        self.COM.setItemText(3, _translate("MainWindow", "COM4"))
        self.COM.setItemText(4, _translate("MainWindow", "COM5"))
        self.COM.setItemText(5, _translate("MainWindow", "COM6"))
        self.pushButton.setText(_translate("MainWindow", "CONNECT"))
        self.label_2.setText(_translate("MainWindow", "Baudrate"))
        self.comboBox.setItemText(0, _translate("MainWindow", "600"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1200"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2400"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4800"))
        self.comboBox.setItemText(4, _translate("MainWindow", "9600"))
        self.comboBox.setItemText(5, _translate("MainWindow", "14400"))
        self.comboBox.setItemText(6, _translate("MainWindow", "19200"))
        self.comboBox.setItemText(7, _translate("MainWindow", "38400"))
        self.comboBox.setItemText(8, _translate("MainWindow", "56000"))
        self.comboBox.setItemText(9, _translate("MainWindow", "57600"))
        self.comboBox.setItemText(10, _translate("MainWindow", "115200"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mode"))
        self.Manual.setText(_translate("MainWindow", "MANUAL"))
        self.Auto.setText(_translate("MainWindow", "AUTO"))
        self.Stop.setText(_translate("MainWindow", "STOP"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Received/Send data"))
        self.re_se_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.send.setText(_translate("MainWindow", "SEND"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GRAPH"))
        self.Manual.setEnabled(False)
        self.Auto.setEnabled(False)
        self.Stop.setEnabled(False)
        self.xaxis.clear()

    def clickedCONNECT(self):
        global comconnect,ser
        NameCOM = self.COM.currentText()
        Baudrate = self.comboBox.currentText()
        try:
            if(comconnect == False):
                self.ser = serial.Serial(NameCOM, Baudrate, timeout=2.5)
                self.COM.setEnabled(False)
                self.comboBox.setEnabled(False)
                self.Manual.setEnabled(True)
                self.Auto.setEnabled(True)
                self.Stop.setEnabled(True)
                self.re_se_data.setEnabled(True)
                self.testsend.setEnabled(True)
                self.send.setEnabled(True)
                self.pushButton.setText('DISCONNECT')
                self.pushButton.setStyleSheet('QPushButton {color: red;}')
                self.re_se_data.append('Serial port ' + NameCOM + ' opened')
                self.timer.start()
                self.timer_getdata.start()
                # self.timer_stop_sys.start()
                comconnect = True 
            else:
                self.COM.setEnabled(True)
                self.comboBox.setEnabled(True)
                self.ser.close()
                self.Manual.setEnabled(False)
                self.Auto.setEnabled(False)
                self.Stop.setEnabled(False)
                self.re_se_data.setEnabled(False)
                self.testsend.setEnabled(False)
                self.send.setEnabled(False)
                self.pushButton.setText('CONNECT')
                self.pushButton.setStyleSheet('QPushButton {color: green;}')
                self.re_se_data.append('Serial port ' + NameCOM + ' closed')
                self.timer.stop()
                self.timer_getdata.stop()
                # self.timer_stop_sys.stop()
                comconnect = False
        except IOError:
            if(comconnect == False):
                self.re_se_data.append('Serial port ' + NameCOM + ' opening error')
            else:
                self.re_se_data.append('Serial port ' + NameCOM + ' closing error')
    

    def clickedSEND(self):
        datasend = self.testsend.toPlainText()
        self.re_se_data.append(datasend)    
        self.ser.write(datasend.encode())

    def clickedManual(self):
        self.timer.start()
        self.Manual.setEnabled(False)
        self.Auto.setEnabled(True)
        self.Stop.setEnabled(True)
        self.re_se_data.append('You are in Manual mode')
        self.ser.write(Manualdata.encode())

    def clickedAuto(self):
        self.timer.start()
        self.Manual.setEnabled(True)
        self.Auto.setEnabled(False)
        self.Stop.setEnabled(True)
        self.re_se_data.append('You are Auto mode')
        self.ser.write(Autodata.encode())

    def clickedStop(self):
        self.timer.stop()
        self.Manual.setEnabled(True)
        self.Auto.setEnabled(True)
        self.re_se_data.append('You stop system')
        self.ser.write(Stopdata.encode())
    
    
    def update(self):
        #update timer
        self.x = self.x[1:]
        self.x.append(self.x[-1] + 1)
        #update value
        self.y = self.y[1:]
        self.y.append(axis[0])
        self.data_line.setData(self.x, self.y)

    def recive(self):
        global axis, ser
        bytetoread=self.ser.inWaiting()
        try:
            if bytetoread>0:
                s = str(self.ser.read(bytetoread),'UTF-8')
                axis[0] = float(s)
                self.re_se_data.append(s)
        except:
            self.re_se_data.append(s + ' is not a number')

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
